name: 'Publish to Rubygems'
description: 'Build a Ruby Gen from a .gemspec file and push it to RubyGems'
inputs:
  rubygems_api_key: 
    description: "API Key to use when publishing the gem"
    required: true
  working_directory:
    description: "Path within the repo to the folder where the .gemspec file lives"
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - name: build gem
      run: |
        cd ${{ inputs.working_directory }}
        gem build -o release.gem
      shell: bash
    - name: publish gem
      env:
        GEM_HOST_API_KEY: ${{ inputs.rubygems_api_key }}
      run: |
        gem push ${{ inputs.working_directory }}/release.gem
      shell: bash