name: Pre-release

# Prepares a new release
#
# To trigger this workflow, simply change the CHANGELOG.md file, replacing the
# "Unreleased" header text with the new release's version number.
#
# The workflow will automatically create a pull request for the release.
#

# We have to run this after the tests, as the tests for this particular action mess
# around with tags and branches, and can confuse this workflow.
on:
  push:
    branches: [main]

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    name: Create / Update Release PR
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: cucumber/action-get-versions@v1.0.0
        id: versions
      - uses: cucumber/action-create-release-pr@v1.0.0
        if: steps.versions.outputs.released-version != steps.versions.outputs.changelog-latest-version
        with:
          released_version: ${{ steps.versions.outputs.released-version }}
          next_version: ${{ steps.versions.outputs.changelog-latest-version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
